apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apply-easy-output-pvc
  namespace: apply-easy
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apply-easy-mlruns-pvc
  namespace: apply-easy
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi
